apiVersion: apps/v1
kind: Deployment
metadata:
  name: upload-play-app
  namespace: upload-play-infra-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: upload-play-app
  template:
    metadata:
      labels:
        app: upload-play-app
    spec:
      containers:
        - name: upload-play-app
          image: julesl123/fabstir-upload-play-example:c7187748925a9eab23e42acce4938890c7d2f06d
          ports:
            - containerPort: 3001
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: DATABASE_URL
          volumeMounts:
            - name: secrets
              mountPath: "/var/run/secrets/my-secret"
              readOnly: true
      volumes:
        - name: secrets
          secret:
            secretName: my-secret
