apiVersion: apps/v1
kind: Deployment
metadata:
  name: upload-play-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: upload-play-app
  template:
    metadata:
      labels:
        app: upload-play-app
    spec:
      containers:
        - name: upload-play-app
          image: julesl123/fabstir-upload-play-example:095de6eb57030c494def8b806e890e1f3dea00d5
          imagePullPolicy: Always
          ports:
            - containerPort: 80
