apiVersion: apps/v1
kind: Deployment
metadata:
  name: upload-play-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: upload-play-app
  template:
    metadata:
      labels:
        app: upload-play-app
    spec:
      containers:
        - name: upload-play-app
          image: julesl123/fabstir-upload-play-example
          imagePullPolicy: Always
          ports:
            - containerPort: 80
