apiVersion: apps/v1
kind: Deployment
metadata:
  name: upload-play-app
  namespace: upload-play-infra-example
spec:
  replicas: 3
  selector:
    matchLabels:
      app: upload-play-app
  template:
    metadata:
      labels:
        app: upload-play-app
    spec:
      containers:
        - name: upload-play-app
          image: julesl123/fabstir-upload-play-example:5dfd4b2d2e5565daec61e6c8fdd281ce1fde605f
          ports:
            - containerPort: 3001
          env:
            - name: PORTAL_URL
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: PORTAL_URL
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: TOKEN
            - name: TRANSCODER_URL
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: TRANSCODER_URL
            - name: TRANSCODE_APP_ENDPOINT
              value: transcode-app.transcode-infra-example.svc.cluster.local:50051
          volumeMounts:
            - name: secrets
              mountPath: "/var/run/secrets/my-secret"
              readOnly: true
      volumes:
        - name: secrets
          secret:
            secretName: my-secret
