apiVersion: v1
kind: Service
metadata:
  name: upload-play-app
spec:
  type: NodePort
  selector:
    app: upload-play-app
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 31000