apiVersion: v1
kind: Service
metadata:
  name: upload-play-app
spec:
  type: NodePort
  selector:
    app: upload-play-app
  ports:
    - port: 3001
      protocol: TCP
      targetPort: 3001
      nodePort: 31000
  externalTrafficPolicy: Local
  endpoints:
  - name: transcode-app
    port: grpc
